steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/tartarus', '.']
images: ['gcr.io/$PROJECT_ID/tartarus']
